Language: c
compiler:
    - gcc
    - clang
branches:
    only:
        - master
        - dev
before_install:
    - sudo apt-get update -qq
install:
    - sudo apt-get install -y nasm openssl libssl-dev cmake libevent-dev libgif-dev libpng-dev libmemcached-dev
script:
    - make
    - cd bin
    - ldd zimg
    - ./zimg conf/zimg.lua
