Language: c
compiler:
    - gcc
    - clang
branches:
    only:
        - master
before_install:
    - sudo apt-get update -qq
install:
    - sudo apt-get install openssl libevent-dev cmake libmagickwand-dev libmemcached-dev
script:
    - make
    - cd bin
    - ./zimg conf/zimg.lua
